### PR TITLE
Axgk

### PR DESCRIPTION
**Pull request by AXGKl**
Hi Jacques, for dir() js and python output is not 100% ident and I guess thats the reason why it is not in right now.
Still, its very often used in intermediate level development, to loop over dynamically created objs, working both in js and python - in contrast to a pragma or a js runtime working construct only.

### CODE REVIEW

**Comment by AXGKl** [comment]
sorry for the conflict, see comments [here](https://github.com/JdeH/Transcrypt/pull/77)

**Comment by JdeH** [comment]
I am in the process of merging your contributions with Transcrypt.

I left out the following piece of text from one of hello/README.md:


    Thats why you have to add the current working directory to have `autotest.py`
    find the testlets *outside* the Python runtime, not within, via `sys.path.insert`.
     
    On POSIX systems this is the standard way: `export PYTHONPATH=".:$PYTHONPATH"`

since I am not sure what's meant here. It is true that the current working directory is added automatically if you use trancsrypt -r, but I am not aware that this has to be done by hand.
Maybe I misunderstood, correct me if I'm wrong.

What one does have to do is:

    import org.transcrypt.autotester

but that's merely an url based import of the autotester itself, that's indeed part of Transcrypt rather than of the CPython installation.

KR
J

**Comment by JdeH** [comment]
If I run the riot example in the browser, output now looks a bit weird to me. Maybe I did something wrong with the manual merge, or is this as it should be:

	Riot Native Tag

	name: n1 - counter: 3

	name: n2 - counter: 4

	Riot Transcrypt Tag Instance <div><h1>Riot Transcrypt Tag Instance {label}</h1> <div> <div> <h5 each="{lv}">name: {name} - counter: {count_up()}</h5> </div> </div></div>

	name: n0 - counter: 2

	name: n1 - counter: 3

	name: n2 - counter: 4

	Riot Transcrypt Tag Instance <div><h1>Riot Transcrypt Tag Instance {label}</h1> <div> <div> <h5 each="{lv}">name: {name} - counter: {count_up()}</h5> </div> </div></div>

	name: n0 - counter: 2

	name: n1 - counter: 3

	name: n2 - counter: 4

	name: n2 - counter: 5

	name: n3 - counter: 6

	name: n4 - counter: 7

	name: n1 - counter: 8

	name: n2 - counter: 9

**Comment by JdeH** [comment]
Two other points:

- I have included riot_demo in the shipment test. In order to do that I've changed the name of the main module to riot_demo.py (since that is what the shipment test currently expects).

- I've moved the dir function from core to builtin. Note that these files use tabs for indentation (to match other, multilanguage projects in which Transcrypt is used). So if you contribute to these files, please use tabs. Any changes I make to your files I'll use spaces. Hope you can live with that...

KR
J

**Comment by AXGKl** [comment]
Hi,
regarding the autotest to me it looks like current dir is *not* added automatically:

```bash
~/GitHub/GKTranscrypt/transcrypt/development/automated_tests/hello $ unset PYTHONPATH        
~/GitHub/GKTranscrypt/transcrypt/development/automated_tests/hello $ transcrypt -r autotest.py
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.199
Copyright (C) Geatec Engineering. License: Apache 2.0

Error: cannot run autotest.py using CPython: No module named 'testlet0'

Aborted
~/GitHub/GKTranscrypt/transcrypt/development/automated_tests/hello $ export PYTHONPATH="."
~/GitHub/GKTranscrypt/transcrypt/development/automated_tests/hello $ transcrypt -r autotest.py
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.199
Copyright (C) Geatec Engineering. License: Apache 2.0
```
Ready
```

**Pull request closed without merging**
